RANDOMNESS:
  torch_seed: 0
  numpy_seed: 0

EXPERIMENT:
  name: "exp"
  exp_path: "experiments"

DATASET_PARAMS:
  db_name: "oil_spill" # dataset name
  db_path: "data/oil_spill_det_dataset" # dataset path


TRAIN_PARAMS:
  num_epochs: 100
  batch_size: 32
  num_workers: 1
  lr: 0.00005
  loss_fn: "default" # default, dice

MODEL_PARAMS:
  model_config: "b0" # b0-5
  checkpoint: ~ # path to checkpoint for resuming training

OUTPUT_PATH:
  weights_path: "weights"
  model_name: "b0.pth"
  inference_path: "result_comparison/segformer"  

